// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.

#ifndef SVN_REVISION_H
#define SVN_REVISION_H

#define BUILD_REVISION 83
#define BUILD_HOST __HOST__
#define BUILD_USER __USER__
#define BUILD_TIME __TIME__
#define BUILD_DATE __DATE__

#endif		 // SVN_REVISION_H

