// This file was automatically generated by the SVN revision extractor.
// There is no need to modify it.

#ifndef SVN_REVISION_H
#define SVN_REVISION_H

static int BUILD_REVISION = 253;

#endif // SVN_REVISION_H
