#!/bin/sh

svn propset svn:eol-style native *.ac
svn propset svn:eol-style native *.sh
svn propset svn:eol-style native */*.pl
svn propset svn:eol-style native *.am
svn propset svn:eol-style native */*.am
svn propset svn:eol-style native */*/*.am
svn propset svn:eol-style native */*/*/*.am
svn propset svn:eol-style native *.cpp
svn propset svn:eol-style native */*.cpp
svn propset svn:eol-style native */*/*.cpp
svn propset svn:eol-style native */*/*/*.cpp
svn propset svn:eol-style native */*/*/*/*.cpp
svn propset svn:eol-style native *.h
svn propset svn:eol-style native */*.h
svn propset svn:eol-style native */*/*.h
svn propset svn:eol-style native */*/*/*.h
svn propset svn:eol-style native */*/*/*/*.h
svn propset svn:eol-style native *.sql
svn propset svn:eol-style native */*.sql
svn propset svn:eol-style native */*/*.sql
svn propset svn:eol-style native */*/*/*.sql
svn propset svn:eol-style native */*/*/*/*.sql
svn propset svn:eol-style native *.txt
svn propset svn:eol-style native */*.txt
svn propset svn:eol-style native */*/*.txt
svn propset svn:eol-style native */*/*/*.txt
svn propset svn:eol-style native */*/*/*/*.txt
