/*
 * Arctic MMORPG Server Software
 * Copyright (c) 2008-2010 Arctic Server Team
 * See COPYING for license details.
 */

#include "AuthServer.h"
/*
NameTableEntry g_authOpcodeNames[] = 
{
	{ RSMSG_AUTH_CHALLENGE, "RSMSG_AUTH_CHALLENGE" },
	{ RCMSG_AUTH_RESPONSE, "RCMSG_AUTH_RESPONSE"  },
	{ RSMSG_AUTH_AUTHORIZED, "RSMSG_AUTH_AUTHORIZED" },
	{ RSMSG_CLIENT_INFORMATION, "RSMSG_CLIENT_INFORMATION" },
	{ RCMSG_CLIENT_INFORMATION, "RCMSG_CLIENT_INFORMATION" },
	{ RSMSG_CLIENT_CLOSE_SESSION, "RSMSG_CLIENT_CLOSE_SESSION" },
	{ RSMSG_PING, "RSMSG_PING" },
	{ RCMSG_PONG, "RCMSG_PONG" },
};
*/
